/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: crpc_protobuf.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "crpc_protobuf.pb-c.h"
void   crpc_message_head__init
                     (CrpcMessageHead         *message)
{
  static const CrpcMessageHead init_value = CRPC_MESSAGE_HEAD__INIT;
  *message = init_value;
}
size_t crpc_message_head__get_packed_size
                     (const CrpcMessageHead *message)
{
  assert(message->base.descriptor == &crpc_message_head__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t crpc_message_head__pack
                     (const CrpcMessageHead *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &crpc_message_head__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t crpc_message_head__pack_to_buffer
                     (const CrpcMessageHead *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &crpc_message_head__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CrpcMessageHead *
       crpc_message_head__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CrpcMessageHead *)
     protobuf_c_message_unpack (&crpc_message_head__descriptor,
                                allocator, len, data);
}
void   crpc_message_head__free_unpacked
                     (CrpcMessageHead *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &crpc_message_head__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   crpc_identity_request__init
                     (CrpcIdentityRequest         *message)
{
  static const CrpcIdentityRequest init_value = CRPC_IDENTITY_REQUEST__INIT;
  *message = init_value;
}
size_t crpc_identity_request__get_packed_size
                     (const CrpcIdentityRequest *message)
{
  assert(message->base.descriptor == &crpc_identity_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t crpc_identity_request__pack
                     (const CrpcIdentityRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &crpc_identity_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t crpc_identity_request__pack_to_buffer
                     (const CrpcIdentityRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &crpc_identity_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CrpcIdentityRequest *
       crpc_identity_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CrpcIdentityRequest *)
     protobuf_c_message_unpack (&crpc_identity_request__descriptor,
                                allocator, len, data);
}
void   crpc_identity_request__free_unpacked
                     (CrpcIdentityRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &crpc_identity_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   crpc_identity_ack__init
                     (CrpcIdentityAck         *message)
{
  static const CrpcIdentityAck init_value = CRPC_IDENTITY_ACK__INIT;
  *message = init_value;
}
size_t crpc_identity_ack__get_packed_size
                     (const CrpcIdentityAck *message)
{
  assert(message->base.descriptor == &crpc_identity_ack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t crpc_identity_ack__pack
                     (const CrpcIdentityAck *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &crpc_identity_ack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t crpc_identity_ack__pack_to_buffer
                     (const CrpcIdentityAck *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &crpc_identity_ack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CrpcIdentityAck *
       crpc_identity_ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CrpcIdentityAck *)
     protobuf_c_message_unpack (&crpc_identity_ack__descriptor,
                                allocator, len, data);
}
void   crpc_identity_ack__free_unpacked
                     (CrpcIdentityAck *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &crpc_identity_ack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   crpc_callback_request__init
                     (CrpcCallbackRequest         *message)
{
  static const CrpcCallbackRequest init_value = CRPC_CALLBACK_REQUEST__INIT;
  *message = init_value;
}
size_t crpc_callback_request__get_packed_size
                     (const CrpcCallbackRequest *message)
{
  assert(message->base.descriptor == &crpc_callback_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t crpc_callback_request__pack
                     (const CrpcCallbackRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &crpc_callback_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t crpc_callback_request__pack_to_buffer
                     (const CrpcCallbackRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &crpc_callback_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CrpcCallbackRequest *
       crpc_callback_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CrpcCallbackRequest *)
     protobuf_c_message_unpack (&crpc_callback_request__descriptor,
                                allocator, len, data);
}
void   crpc_callback_request__free_unpacked
                     (CrpcCallbackRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &crpc_callback_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   crpc_callback_ack__init
                     (CrpcCallbackAck         *message)
{
  static const CrpcCallbackAck init_value = CRPC_CALLBACK_ACK__INIT;
  *message = init_value;
}
size_t crpc_callback_ack__get_packed_size
                     (const CrpcCallbackAck *message)
{
  assert(message->base.descriptor == &crpc_callback_ack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t crpc_callback_ack__pack
                     (const CrpcCallbackAck *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &crpc_callback_ack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t crpc_callback_ack__pack_to_buffer
                     (const CrpcCallbackAck *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &crpc_callback_ack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CrpcCallbackAck *
       crpc_callback_ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CrpcCallbackAck *)
     protobuf_c_message_unpack (&crpc_callback_ack__descriptor,
                                allocator, len, data);
}
void   crpc_callback_ack__free_unpacked
                     (CrpcCallbackAck *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &crpc_callback_ack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor crpc_message_head__field_descriptors[4] =
{
  {
    "magic",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CrpcMessageHead, magic),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CrpcMessageHead, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CrpcMessageHead, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CrpcMessageHead, content),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned crpc_message_head__field_indices_by_name[] = {
  3,   /* field[3] = content */
  0,   /* field[0] = magic */
  1,   /* field[1] = name */
  2,   /* field[2] = type */
};
static const ProtobufCIntRange crpc_message_head__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor crpc_message_head__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "crpc_message_head",
  "CrpcMessageHead",
  "CrpcMessageHead",
  "",
  sizeof(CrpcMessageHead),
  4,
  crpc_message_head__field_descriptors,
  crpc_message_head__field_indices_by_name,
  1,  crpc_message_head__number_ranges,
  (ProtobufCMessageInit) crpc_message_head__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor crpc_identity_request__field_descriptors[1] =
{
  {
    "operate",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CrpcIdentityRequest, operate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned crpc_identity_request__field_indices_by_name[] = {
  0,   /* field[0] = operate */
};
static const ProtobufCIntRange crpc_identity_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor crpc_identity_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "crpc_identity_request",
  "CrpcIdentityRequest",
  "CrpcIdentityRequest",
  "",
  sizeof(CrpcIdentityRequest),
  1,
  crpc_identity_request__field_descriptors,
  crpc_identity_request__field_indices_by_name,
  1,  crpc_identity_request__number_ranges,
  (ProtobufCMessageInit) crpc_identity_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor crpc_identity_ack__field_descriptors[1] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CrpcIdentityAck, result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned crpc_identity_ack__field_indices_by_name[] = {
  0,   /* field[0] = result */
};
static const ProtobufCIntRange crpc_identity_ack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor crpc_identity_ack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "crpc_identity_ack",
  "CrpcIdentityAck",
  "CrpcIdentityAck",
  "",
  sizeof(CrpcIdentityAck),
  1,
  crpc_identity_ack__field_descriptors,
  crpc_identity_ack__field_indices_by_name,
  1,  crpc_identity_ack__number_ranges,
  (ProtobufCMessageInit) crpc_identity_ack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor crpc_callback_request__field_descriptors[2] =
{
  {
    "callback_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CrpcCallbackRequest, callback_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "paramete",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CrpcCallbackRequest, has_paramete),
    offsetof(CrpcCallbackRequest, paramete),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned crpc_callback_request__field_indices_by_name[] = {
  0,   /* field[0] = callback_id */
  1,   /* field[1] = paramete */
};
static const ProtobufCIntRange crpc_callback_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor crpc_callback_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "crpc_callback_request",
  "CrpcCallbackRequest",
  "CrpcCallbackRequest",
  "",
  sizeof(CrpcCallbackRequest),
  2,
  crpc_callback_request__field_descriptors,
  crpc_callback_request__field_indices_by_name,
  1,  crpc_callback_request__number_ranges,
  (ProtobufCMessageInit) crpc_callback_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor crpc_callback_ack__field_descriptors[2] =
{
  {
    "callback_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CrpcCallbackAck, callback_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "result",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CrpcCallbackAck, has_result),
    offsetof(CrpcCallbackAck, result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned crpc_callback_ack__field_indices_by_name[] = {
  0,   /* field[0] = callback_id */
  1,   /* field[1] = result */
};
static const ProtobufCIntRange crpc_callback_ack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor crpc_callback_ack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "crpc_callback_ack",
  "CrpcCallbackAck",
  "CrpcCallbackAck",
  "",
  sizeof(CrpcCallbackAck),
  2,
  crpc_callback_ack__field_descriptors,
  crpc_callback_ack__field_indices_by_name,
  1,  crpc_callback_ack__number_ranges,
  (ProtobufCMessageInit) crpc_callback_ack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
