/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: crpc_protobuf.proto */

#ifndef PROTOBUF_C_crpc_5fprotobuf_2eproto__INCLUDED
#define PROTOBUF_C_crpc_5fprotobuf_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _CrpcMsg CrpcMsg;


/* --- enums --- */


/* --- messages --- */

struct  _CrpcMsg
{
  ProtobufCMessage base;
  uint32_t magic;
  uint32_t operate;
};
#define CRPC_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&crpc_msg__descriptor) \
    , 0, 0 }


/* CrpcMsg methods */
void   crpc_msg__init
                     (CrpcMsg         *message);
size_t crpc_msg__get_packed_size
                     (const CrpcMsg   *message);
size_t crpc_msg__pack
                     (const CrpcMsg   *message,
                      uint8_t             *out);
size_t crpc_msg__pack_to_buffer
                     (const CrpcMsg   *message,
                      ProtobufCBuffer     *buffer);
CrpcMsg *
       crpc_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   crpc_msg__free_unpacked
                     (CrpcMsg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CrpcMsg_Closure)
                 (const CrpcMsg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor crpc_msg__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_crpc_5fprotobuf_2eproto__INCLUDED */
