/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: crpc_protobuf.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "crpc_protobuf.pb-c.h"
void   crpc_message_head__init
                     (CrpcMessageHead         *message)
{
  static const CrpcMessageHead init_value = CRPC_MESSAGE_HEAD__INIT;
  *message = init_value;
}
size_t crpc_message_head__get_packed_size
                     (const CrpcMessageHead *message)
{
  assert(message->base.descriptor == &crpc_message_head__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t crpc_message_head__pack
                     (const CrpcMessageHead *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &crpc_message_head__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t crpc_message_head__pack_to_buffer
                     (const CrpcMessageHead *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &crpc_message_head__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CrpcMessageHead *
       crpc_message_head__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CrpcMessageHead *)
     protobuf_c_message_unpack (&crpc_message_head__descriptor,
                                allocator, len, data);
}
void   crpc_message_head__free_unpacked
                     (CrpcMessageHead *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &crpc_message_head__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   crpc_message_ack__init
                     (CrpcMessageAck         *message)
{
  static const CrpcMessageAck init_value = CRPC_MESSAGE_ACK__INIT;
  *message = init_value;
}
size_t crpc_message_ack__get_packed_size
                     (const CrpcMessageAck *message)
{
  assert(message->base.descriptor == &crpc_message_ack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t crpc_message_ack__pack
                     (const CrpcMessageAck *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &crpc_message_ack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t crpc_message_ack__pack_to_buffer
                     (const CrpcMessageAck *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &crpc_message_ack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CrpcMessageAck *
       crpc_message_ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CrpcMessageAck *)
     protobuf_c_message_unpack (&crpc_message_ack__descriptor,
                                allocator, len, data);
}
void   crpc_message_ack__free_unpacked
                     (CrpcMessageAck *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &crpc_message_ack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   crpc_callback_request__init
                     (CrpcCallbackRequest         *message)
{
  static const CrpcCallbackRequest init_value = CRPC_CALLBACK_REQUEST__INIT;
  *message = init_value;
}
size_t crpc_callback_request__get_packed_size
                     (const CrpcCallbackRequest *message)
{
  assert(message->base.descriptor == &crpc_callback_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t crpc_callback_request__pack
                     (const CrpcCallbackRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &crpc_callback_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t crpc_callback_request__pack_to_buffer
                     (const CrpcCallbackRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &crpc_callback_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CrpcCallbackRequest *
       crpc_callback_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CrpcCallbackRequest *)
     protobuf_c_message_unpack (&crpc_callback_request__descriptor,
                                allocator, len, data);
}
void   crpc_callback_request__free_unpacked
                     (CrpcCallbackRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &crpc_callback_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   crpc_callback_response__init
                     (CrpcCallbackResponse         *message)
{
  static const CrpcCallbackResponse init_value = CRPC_CALLBACK_RESPONSE__INIT;
  *message = init_value;
}
size_t crpc_callback_response__get_packed_size
                     (const CrpcCallbackResponse *message)
{
  assert(message->base.descriptor == &crpc_callback_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t crpc_callback_response__pack
                     (const CrpcCallbackResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &crpc_callback_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t crpc_callback_response__pack_to_buffer
                     (const CrpcCallbackResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &crpc_callback_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CrpcCallbackResponse *
       crpc_callback_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CrpcCallbackResponse *)
     protobuf_c_message_unpack (&crpc_callback_response__descriptor,
                                allocator, len, data);
}
void   crpc_callback_response__free_unpacked
                     (CrpcCallbackResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &crpc_callback_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   crpc_callback_register__init
                     (CrpcCallbackRegister         *message)
{
  static const CrpcCallbackRegister init_value = CRPC_CALLBACK_REGISTER__INIT;
  *message = init_value;
}
size_t crpc_callback_register__get_packed_size
                     (const CrpcCallbackRegister *message)
{
  assert(message->base.descriptor == &crpc_callback_register__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t crpc_callback_register__pack
                     (const CrpcCallbackRegister *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &crpc_callback_register__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t crpc_callback_register__pack_to_buffer
                     (const CrpcCallbackRegister *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &crpc_callback_register__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CrpcCallbackRegister *
       crpc_callback_register__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CrpcCallbackRegister *)
     protobuf_c_message_unpack (&crpc_callback_register__descriptor,
                                allocator, len, data);
}
void   crpc_callback_register__free_unpacked
                     (CrpcCallbackRegister *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &crpc_callback_register__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   crpc_callback_register_return__init
                     (CrpcCallbackRegisterReturn         *message)
{
  static const CrpcCallbackRegisterReturn init_value = CRPC_CALLBACK_REGISTER_RETURN__INIT;
  *message = init_value;
}
size_t crpc_callback_register_return__get_packed_size
                     (const CrpcCallbackRegisterReturn *message)
{
  assert(message->base.descriptor == &crpc_callback_register_return__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t crpc_callback_register_return__pack
                     (const CrpcCallbackRegisterReturn *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &crpc_callback_register_return__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t crpc_callback_register_return__pack_to_buffer
                     (const CrpcCallbackRegisterReturn *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &crpc_callback_register_return__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CrpcCallbackRegisterReturn *
       crpc_callback_register_return__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CrpcCallbackRegisterReturn *)
     protobuf_c_message_unpack (&crpc_callback_register_return__descriptor,
                                allocator, len, data);
}
void   crpc_callback_register_return__free_unpacked
                     (CrpcCallbackRegisterReturn *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &crpc_callback_register_return__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor crpc_message_head__field_descriptors[4] =
{
  {
    "magic",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CrpcMessageHead, magic),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CrpcMessageHead, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg_id",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CrpcMessageHead, msg_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CrpcMessageHead, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned crpc_message_head__field_indices_by_name[] = {
  0,   /* field[0] = magic */
  2,   /* field[2] = msg_id */
  3,   /* field[3] = name */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange crpc_message_head__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor crpc_message_head__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "crpc_message_head",
  "CrpcMessageHead",
  "CrpcMessageHead",
  "",
  sizeof(CrpcMessageHead),
  4,
  crpc_message_head__field_descriptors,
  crpc_message_head__field_indices_by_name,
  1,  crpc_message_head__number_ranges,
  (ProtobufCMessageInit) crpc_message_head__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor crpc_message_ack__field_descriptors[3] =
{
  {
    "head",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CrpcMessageAck, head),
    &crpc_message_head__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "result",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CrpcMessageAck, result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "description",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CrpcMessageAck, description),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned crpc_message_ack__field_indices_by_name[] = {
  2,   /* field[2] = description */
  0,   /* field[0] = head */
  1,   /* field[1] = result */
};
static const ProtobufCIntRange crpc_message_ack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor crpc_message_ack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "crpc_message_ack",
  "CrpcMessageAck",
  "CrpcMessageAck",
  "",
  sizeof(CrpcMessageAck),
  3,
  crpc_message_ack__field_descriptors,
  crpc_message_ack__field_indices_by_name,
  1,  crpc_message_ack__number_ranges,
  (ProtobufCMessageInit) crpc_message_ack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor crpc_callback_request__field_descriptors[3] =
{
  {
    "head",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CrpcCallbackRequest, head),
    &crpc_message_head__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "callback_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CrpcCallbackRequest, callback_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parameters",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CrpcCallbackRequest, has_parameters),
    offsetof(CrpcCallbackRequest, parameters),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned crpc_callback_request__field_indices_by_name[] = {
  1,   /* field[1] = callback_id */
  0,   /* field[0] = head */
  2,   /* field[2] = parameters */
};
static const ProtobufCIntRange crpc_callback_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor crpc_callback_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "crpc_callback_request",
  "CrpcCallbackRequest",
  "CrpcCallbackRequest",
  "",
  sizeof(CrpcCallbackRequest),
  3,
  crpc_callback_request__field_descriptors,
  crpc_callback_request__field_indices_by_name,
  1,  crpc_callback_request__number_ranges,
  (ProtobufCMessageInit) crpc_callback_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor crpc_callback_response__field_descriptors[2] =
{
  {
    "callback_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CrpcCallbackResponse, callback_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "result",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CrpcCallbackResponse, has_result),
    offsetof(CrpcCallbackResponse, result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned crpc_callback_response__field_indices_by_name[] = {
  0,   /* field[0] = callback_id */
  1,   /* field[1] = result */
};
static const ProtobufCIntRange crpc_callback_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor crpc_callback_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "crpc_callback_response",
  "CrpcCallbackResponse",
  "CrpcCallbackResponse",
  "",
  sizeof(CrpcCallbackResponse),
  2,
  crpc_callback_response__field_descriptors,
  crpc_callback_response__field_indices_by_name,
  1,  crpc_callback_response__number_ranges,
  (ProtobufCMessageInit) crpc_callback_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor crpc_callback_register__field_descriptors[1] =
{
  {
    "register_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CrpcCallbackRegister, register_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned crpc_callback_register__field_indices_by_name[] = {
  0,   /* field[0] = register_id */
};
static const ProtobufCIntRange crpc_callback_register__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor crpc_callback_register__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "crpc_callback_register",
  "CrpcCallbackRegister",
  "CrpcCallbackRegister",
  "",
  sizeof(CrpcCallbackRegister),
  1,
  crpc_callback_register__field_descriptors,
  crpc_callback_register__field_indices_by_name,
  1,  crpc_callback_register__number_ranges,
  (ProtobufCMessageInit) crpc_callback_register__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor crpc_callback_register_return__field_descriptors[1] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CrpcCallbackRegisterReturn, result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned crpc_callback_register_return__field_indices_by_name[] = {
  0,   /* field[0] = result */
};
static const ProtobufCIntRange crpc_callback_register_return__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor crpc_callback_register_return__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "crpc_callback_register_return",
  "CrpcCallbackRegisterReturn",
  "CrpcCallbackRegisterReturn",
  "",
  sizeof(CrpcCallbackRegisterReturn),
  1,
  crpc_callback_register_return__field_descriptors,
  crpc_callback_register_return__field_indices_by_name,
  1,  crpc_callback_register_return__number_ranges,
  (ProtobufCMessageInit) crpc_callback_register_return__init,
  NULL,NULL,NULL    /* reserved[123] */
};
