SOURCES_FILE = \
			   /home/crpc/src/utils/buffer.c \
			   /home/crpc/src/utils/log.c \



INCLUDE_DIR = \
			  -I/home/crpc/src/includes

cli0:
	gcc -g -o $@ crpc_client0.c $(SOURCES_FILE) $(INCLUDE_DIR)

clean:
	-rm cli0 
