SOURCES_FILE = \
			   /home/panda/src/utils/buffer.c \
			   /home/panda/src/utils/list.c \
			   /home/panda/src/utils/log.c \
			   /home/panda/src/utils/hash.c \
			   /home/panda/src/utils/tlv.c 


INCLUDE_DIR = \
			  -I/home/panda/src/includes

srv:
	gcc -g -o $@ crpc_server.c $(SOURCES_FILE) $(INCLUDE_DIR)

cli:
	gcc -g -o $@ panda_client.c $(SOURCES_FILE) $(INCLUDE_DIR)

clean:
	-rm srv cli 
